# Generated by Django 6.0 on 2025-12-13 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idcurso', models.AutoField(db_column='idCurso', primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(db_column='Nome_curso', max_length=45)),
                ('imagem', models.ImageField(blank=True, db_column='imagem_curso', null=True, upload_to='curso/')),
                ('descricao_curso', models.CharField(blank=True, db_column='Descricao_curso', max_length=100, null=True)),
                ('data_inicio', models.DateField(blank=True, db_column='Data_inicio', null=True)),
                ('data_final', models.DateField(blank=True, db_column='Data_final', null=True)),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('idforum', models.AutoField(db_column='idForum', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=30)),
                ('data_criacao', models.DateField(db_column='Data_criacao')),
            ],
            options={
                'db_table': 'forum',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, db_column='imagem_usuario', null=True, upload_to='usuarios/')),
                ('tipo', models.CharField(db_column='Tipo', max_length=11)),
                ('nome', models.CharField(db_column='Nome', max_length=20)),
                ('sobrenome', models.CharField(db_column='Sobrenome', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=45)),
                ('senha', models.CharField(db_column='Senha', max_length=128)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=100, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('idturma', models.AutoField(db_column='idTurma', primary_key=True, serialize=False)),
                ('codigo_turma', models.CharField(db_column='Codigo_Turma', max_length=11)),
                ('turno', models.CharField(blank=True, db_column='Turno', max_length=5, null=True)),
                ('ano', models.IntegerField(db_column='Ano')),
                ('curso', models.ForeignKey(db_column='ID_Curso', on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.curso')),
            ],
            options={
                'db_table': 'turma',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('idprojeto', models.AutoField(db_column='idProjeto', primary_key=True, serialize=False)),
                ('nome_projeto', models.CharField(db_column='Nome_projeto', max_length=30)),
                ('data_de_criacao', models.DateField(auto_now_add=True)),
                ('data_de_modificacao', models.DateField(auto_now=True)),
                ('turma', models.ForeignKey(db_column='ID_Turma', on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.turma')),
            ],
            options={
                'db_table': 'projeto',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(db_column='Conteudo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='Data_criacao')),
                ('forum', models.ForeignKey(db_column='ID_Forum', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='InovaEdu.forum')),
                ('autor', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.usuario')),
            ],
            options={
                'db_table': 'mensagem',
            },
        ),
        migrations.AddField(
            model_name='forum',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='ID_Usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='InovaEdu.usuario'),
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('ideventos', models.AutoField(db_column='idEventos', primary_key=True, serialize=False)),
                ('nome_do_evento', models.CharField(db_column='Nome_do_evento', max_length=30)),
                ('hora_do_evento', models.TimeField(db_column='Hora_do_evento')),
                ('data_do_evento', models.DateField(db_column='Data_do_evento')),
                ('descricao', models.CharField(db_column='Descricao', max_length=100)),
                ('endereco', models.CharField(db_column='Endereco', max_length=30)),
                ('usuario', models.ForeignKey(blank=True, db_column='ID_Usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='InovaEdu.usuario')),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='ID_Usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='InovaEdu.usuario'),
        ),
        migrations.CreateModel(
            name='UsuarioDaTurma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_turma', models.ForeignKey(db_column='ID_Turma', on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.turma')),
                ('id_usuario', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.usuario')),
            ],
            options={
                'db_table': 'usuario_da_turma',
                'unique_together': {('id_usuario', 'id_turma')},
            },
        ),
    ]
