# Generated by Django 5.2.6 on 2025-12-12 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idcurso', models.AutoField(db_column='idCurso', primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(db_column='Nome_curso', max_length=45)),
                ('imagem', models.ImageField(blank=True, db_column='imagem_curso', null=True, upload_to='curso/')),
                ('descricao_curso', models.CharField(blank=True, db_column='Descricao_curso', max_length=100, null=True)),
                ('data_inicio', models.DateField(blank=True, db_column='Data_inicio', null=True)),
                ('data_final', models.DateField(blank=True, db_column='Data_final', null=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('ideventos', models.AutoField(db_column='idEventos', primary_key=True, serialize=False)),
                ('nome_do_evento', models.CharField(db_column='Nome_do_evento', max_length=30)),
                ('hora_do_evento', models.TimeField(db_column='Hora_do_evento')),
                ('data_do_evento', models.DateField(db_column='Data_do_evento')),
                ('descricao', models.CharField(db_column='Descricao', max_length=100)),
                ('endereco', models.CharField(db_column='Endereco', max_length=30)),
            ],
            options={
                'db_table': 'eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, db_column='imagem_usuario', null=True, upload_to='usuarios/')),
                ('tipo', models.CharField(db_column='Tipo', max_length=11)),
                ('nome', models.CharField(db_column='Nome', max_length=20)),
                ('sobrenome', models.CharField(db_column='Sobrenome', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=45)),
                ('senha', models.CharField(db_column='Senha', max_length=30)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=100, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioDaTurma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_da_turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('idforum', models.AutoField(db_column='idForum', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=30)),
                ('data_criacao', models.DateField(db_column='Data_criacao')),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=30, null=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='ID_Usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.usuario')),
            ],
            options={
                'db_table': 'forum',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(db_column='Conteudo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='Data_criacao')),
                ('autor', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.usuario')),
                ('forum', models.ForeignKey(db_column='ID_Forum', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='InovaEdu.forum')),
            ],
            options={
                'db_table': 'mensagem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('idturma', models.AutoField(db_column='idTurma', primary_key=True, serialize=False)),
                ('codigo_turma', models.CharField(db_column='Codigo_Turma', max_length=11)),
                ('turno', models.CharField(blank=True, db_column='Turno', max_length=5, null=True)),
                ('ano', models.IntegerField(db_column='Ano')),
                ('curso', models.ForeignKey(db_column='ID_Curso', on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.curso')),
            ],
            options={
                'db_table': 'turma',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('idprojeto', models.AutoField(db_column='idProjeto', primary_key=True, serialize=False)),
                ('nome_projeto', models.CharField(db_column='Nome_projeto', max_length=30)),
                ('data_de_criacao', models.DateField(auto_now_add=True)),
                ('data_de_modificacao', models.DateField(auto_now=True)),
                ('turma', models.ForeignKey(db_column='ID_Turma', on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.turma')),
            ],
            options={
                'db_table': 'projeto',
            },
        ),
    ]
