# Generated by Django 6.0 on 2026-03-17 17:32

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idcurso', models.AutoField(db_column='idCurso', primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(db_column='Nome_curso', max_length=45)),
                ('imagem', cloudinary.models.CloudinaryField(blank=True, db_column='imagem_curso', max_length=255, null=True, verbose_name='imagem_curso')),
                ('descricao_curso', models.CharField(blank=True, db_column='Descricao_curso', max_length=100, null=True)),
                ('data_inicio', models.DateField(blank=True, db_column='Data_inicio', null=True)),
                ('data_final', models.DateField(blank=True, db_column='Data_final', null=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('idforum', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forum',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('idprojeto', models.AutoField(db_column='idProjeto', primary_key=True, serialize=False)),
                ('nome_projeto', models.CharField(db_column='Nome_projeto', max_length=30)),
                ('descricao', models.TextField(blank=True, db_column='Descricao', null=True)),
                ('imagem', cloudinary.models.CloudinaryField(blank=True, db_column='Imagem', max_length=255, null=True, verbose_name='imagem_projeto')),
                ('data_de_criacao', models.DateField(auto_now_add=True)),
                ('data_de_modificacao', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'projeto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('imagem', cloudinary.models.CloudinaryField(blank=True, db_column='imagem_usuario', max_length=255, null=True, verbose_name='imagem_usuario')),
                ('tipo', models.CharField(db_column='Tipo', max_length=11)),
                ('nome', models.CharField(db_column='Nome', max_length=20)),
                ('sobrenome', models.CharField(db_column='Sobrenome', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=45)),
                ('senha', models.CharField(db_column='Senha', max_length=30)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=100, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('pasta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='InovaEdu.pasta')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.projeto')),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.usuario')),
            ],
            options={
                'db_table': 'pasta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('idtopico', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=100)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='InovaEdu.forum')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.usuario')),
            ],
            options={
                'db_table': 'topico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('idturma', models.AutoField(db_column='idTurma', primary_key=True, serialize=False)),
                ('codigo_turma', models.CharField(db_column='Codigo_Turma', max_length=11)),
                ('turno', models.CharField(blank=True, db_column='Turno', max_length=5, null=True)),
                ('ano', models.IntegerField(db_column='Ano')),
                ('curso', models.ForeignKey(db_column='ID_Curso', on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.curso')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='InovaEdu.usuario')),
            ],
            options={
                'db_table': 'turma',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='turma',
            field=models.ForeignKey(db_column='ID_Turma', on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.turma'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='InovaEdu.usuario'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='alunos_edicao',
            field=models.ManyToManyField(blank=True, related_name='projetos_edicao', to='InovaEdu.usuario'),
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluida', models.BooleanField(default=False)),
                ('conteudo', models.TextField(db_column='Conteudo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='Data_criacao')),
                ('topico', models.ForeignKey(db_column='ID_Topico', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='InovaEdu.topico')),
                ('autor', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.usuario')),
            ],
            options={
                'db_table': 'mensagem',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='forum',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.usuario'),
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('ideventos', models.AutoField(db_column='idEventos', primary_key=True, serialize=False)),
                ('nome_do_evento', models.CharField(db_column='Nome_do_evento', max_length=50)),
                ('hora_do_evento', models.TimeField(db_column='Hora_do_evento')),
                ('data_do_evento', models.DateField(db_column='Data_do_evento')),
                ('descricao', models.CharField(db_column='Descricao', max_length=100)),
                ('endereco', models.CharField(db_column='Endereco', max_length=30)),
                ('usuario', models.ForeignKey(blank=True, db_column='ID_Usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.usuario')),
            ],
            options={
                'db_table': 'eventos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='ID_Usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.usuario'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('idcertificado', models.AutoField(db_column='idCertificado', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=150, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='InovaEdu.usuario')),
            ],
            options={
                'db_table': 'certificado',
            },
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='arquivo')),
                ('resource_type', models.CharField(blank=True, max_length=20, null=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('pasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.pasta')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.projeto')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.usuario')),
            ],
            options={
                'db_table': 'arquivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioDaTurma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_turma', models.ForeignKey(db_column='ID_Turma', on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.turma')),
                ('id_usuario', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.usuario')),
            ],
            options={
                'db_table': 'usuario_da_turma',
                'managed': True,
                'unique_together': {('id_usuario', 'id_turma')},
            },
        ),
    ]
