# Generated by Django 6.0 on 2025-12-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='curso',
            field=models.ForeignKey(blank=True, db_column='ID_Curso', null=True, on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.curso'),
        ),
    ]
