# Generated by Django 6.0 on 2026-01-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='resource_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
