# Generated by Django 5.2.6 on 2025-12-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='descricao',
            field=models.CharField(blank=True, db_column='Descricao', max_length=30, null=True),
        ),
    ]
