# Generated by Django 6.0 on 2026-01-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='InovaEdu.usuario'),
        ),
    ]
