# Generated by Django 5.2.6 on 2025-10-30 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(db_column='Conteudo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='Data_criacao')),
                ('autor', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.usuario')),
                ('forum', models.ForeignKey(db_column='ID_Forum', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='InovaEdu.forum')),
            ],
            options={
                'db_table': 'mensagem',
                'managed': True,
            },
        ),
    ]
