# Generated by Django 6.0 on 2026-01-05 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='arquivo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pasta',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuariodaturma',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.pasta'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='data_criacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='forum',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.usuario'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='autor',
            field=models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.usuario'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(db_column='Conteudo'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_column='Data_criacao'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='forum',
            field=models.ForeignKey(db_column='ID_Forum', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='InovaEdu.forum'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='idprojeto',
            field=models.AutoField(db_column='idProjeto', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome_projeto',
            field=models.CharField(db_column='Nome_projeto', max_length=30),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='turma',
            field=models.ForeignKey(db_column='ID_Turma', on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ano',
            field=models.IntegerField(db_column='Ano'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='codigo_turma',
            field=models.CharField(db_column='Codigo_Turma', max_length=11),
        ),
        migrations.AlterField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(db_column='ID_Curso', on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.curso'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='idturma',
            field=models.AutoField(db_column='idTurma', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(blank=True, db_column='Turno', max_length=5, null=True),
        ),
    ]
