# Generated by Django 6.0 on 2026-01-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='forum',
        ),
    ]
