# Generated by Django 6.0 on 2026-01-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='resource_type',
            field=models.CharField(default='auto', max_length=20),
        ),
    ]
