# Generated by Django 6.0 on 2025-12-23 23:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='arquivo'),
        ),
    ]
