# Generated by Django 6.0 on 2026-01-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0002_arquivo_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
