# Generated by Django 6.0 on 2026-01-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0002_authusergroups_authuseruserpermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='topico',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuariodaturma',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='forum',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
