# Generated by Django 6.0 on 2026-01-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0002_projeto_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='turma',
        ),
    ]
