# Generated by Django 5.2.6 on 2025-11-28 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0002_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('idpasta', models.AutoField(db_column='idPasta', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('pasta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.pasta')),
            ],
            options={
                'db_table': 'pasta',
            },
        ),
    ]
