# Generated by Django 6.0 on 2026-08-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0002_alter_certificado_nome_alter_projeto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(db_column='Senha', max_length=128),
        ),
    ]
