# Generated by Django 6.0 on 2026-01-12 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0003_arquivo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.usuario'),
        ),
    ]
