# Generated by Django 6.0 on 2026-01-01 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('idtopico', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='InovaEdu.forum')),
            ],
            options={
                'db_table': 'topico',
            },
        ),
    ]
