# Generated by Django 5.2.6 on 2025-11-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0003_pasta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={},
        ),
    ]
