# Generated by Django 6.0 on 2026-01-01 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0004_topico'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='data_criacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='forum',
            name='idforum',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forum',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='forum',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.usuario'),
        ),
    ]
