# Generated by Django 6.0 on 2026-01-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0004_turma_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, db_column='Descricao', null=True),
        ),
    ]
