# Generated by Django 6.0 on 2026-01-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0004_topico_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='nome_do_evento',
            field=models.CharField(db_column='Nome_do_evento', max_length=50),
        ),
    ]
