# Generated by Django 5.2.6 on 2025-11-28 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0004_alter_projeto_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='caminho_do_arquivo',
        ),
        migrations.AddField(
            model_name='projeto',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='projetos/'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InovaEdu.pasta'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='turma',
            field=models.ForeignKey(blank=True, db_column='ID_Turma', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.turma'),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='pasta_pai',
            field=models.ForeignKey(blank=True, db_column='pasta_pai_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='InovaEdu.pasta'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_de_criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_de_modificacao',
            field=models.DateField(auto_now=True),
        ),
    ]
