# Generated by Django 6.0 on 2026-01-19 23:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0005_projeto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='alunos',
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, db_column='Imagem', max_length=255, null=True, verbose_name='imagem_projeto'),
        ),
    ]
