# Generated by Django 6.0 on 2026-01-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0005_forum_descricao_alter_forum_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='descricao',
        ),
        migrations.AddField(
            model_name='topico',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
