# Generated by Django 5.2.6 on 2025-11-28 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0005_remove_projeto_caminho_do_arquivo_projeto_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='turma',
            field=models.ForeignKey(db_column='ID_Turma', on_delete=django.db.models.deletion.DO_NOTHING, to='InovaEdu.turma'),
        ),
    ]
