# Generated by Django 6.0 on 2026-01-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0007_projeto_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='alunos',
        ),
        migrations.AddField(
            model_name='projeto',
            name='alunos_edicao',
            field=models.ManyToManyField(blank=True, related_name='projetos_edicao', to='InovaEdu.usuario'),
        ),
    ]
