# Generated by Django 6.0 on 2026-01-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0008_remove_projeto_alunos_projeto_alunos_edicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='InovaEdu.usuario'),
        ),
    ]
