# Generated by Django 6.0 on 2026-03-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0009_projeto_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='excluida',
            field=models.BooleanField(default=False),
        ),
    ]
