# Generated by Django 6.0 on 2026-03-03 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InovaEdu', '0009_projeto_alunos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('idcertificado', models.AutoField(db_column='idCertificado', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=150, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='InovaEdu.usuario')),
            ],
            options={
                'db_table': 'certificado',
            },
        ),
    ]
